<?php

use Illuminate\Database\Seeder;

class EmployeesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('employees')->delete();
        
        \DB::table('employees')->insert(array (
            0 => 
            array (
                'id' => 1,
                'employee_id' => '000964',
                'name' => 'Kufre Akpabio',
                'position' => 'Admin Officer',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-27 00:00:00',
                'updated_at' => '2019-07-27 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'employee_id' => '002349',
                'name' => 'ADEBAYO NASIR MUSTAPHA',
                'position' => 'COST CONTROL OFFICE',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => '2019-07-29 17:40:46',
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 17:40:46',
            ),
            2 => 
            array (
                'id' => 3,
                'employee_id' => '003320',
                'name' => 'Edidiong  Marcus Etokeren',
                'position' => 'procurement officer',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'employee_id' => '1401',
                'name' => 'Alhassan Ahmad',
                'position' => 'Admin Assistan',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'employee_id' => '001814',
                'name' => 'Aniekan Samuel Peter',
                'position' => 'Safety Supervisor',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'employee_id' => '00043',
                'name' => 'Anthony Edward Inuen',
                'position' => 'QA/QC Engineer',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'employee_id' => '001575',
                'name' => 'Chimobi Kingsley Ihunwo',
                'position' => 'Human Resources Officer',
                'project_id' => 12,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'employee_id' => '002522',
                'name' => 'Clara Chinyere Okorie',
                'position' => 'procurement officer',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'employee_id' => '002349',
                'name' => 'Adebayo Nasir Mustapha',
                'position' => 'Cost Control Officer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'employee_id' => '002523',
                'name' => 'Edidiong Ekerete Ebienye',
                'position' => 'Acounting Officer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 01:00:00',
                'updated_at' => '2019-07-29 01:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'employee_id' => '003112',
                'name' => 'Alice  Dickson',
                'position' => 'Accounting Assistant',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'employee_id' => '001201',
                'name' => 'Fidelis Chukwu  Nweke',
                'position' => 'Accunting  Officer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'employee_id' => '02528',
                'name' => 'Halil Bulbul',
                'position' => 'HR/ADMIN  Chief',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'employee_id' => '02267',
                'name' => 'Akpanaman Ifiok Ezekiel',
                'position' => 'Cost Control Officer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'employee_id' => '02224',
                'name' => 'Item Nkereuwem  Sunday',
                'position' => 'Accounting Intern',
                'project_id' => 10,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'employee_id' => '000924',
                'name' => 'Kufre  Sunday  AKpabio',
                'position' => 'Admin Assistan',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'employee_id' => '002356',
                'name' => 'Joseph  Abraham',
                'position' => 'Procurement Officer',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'employee_id' => '002764',
                'name' => 'Owoedinyene  Monday Etuk',
                'position' => 'Quantiity Surveyor',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'employee_id' => '1334',
                'name' => 'Nehemiah  John',
                'position' => 'Electrical  Engineer',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'employee_id' => '00010',
                'name' => 'Nse Udo  Nkpembe',
                'position' => 'Human Resources Officer',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => '2019-07-30 08:07:30',
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 08:07:30',
            ),
            20 => 
            array (
                'id' => 21,
                'employee_id' => '000102',
                'name' => 'Nse Udo  Nkpembe',
                'position' => 'Human Resources Officer',
                'project_id' => 12,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'employee_id' => '00689',
                'name' => 'Nsisong  Ibanga',
                'position' => 'Warehouse Woker',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            22 => 
            array (
                'id' => 23,
                'employee_id' => '002678',
                'name' => 'Ozan Aslan',
                'position' => 'Personel Specialist',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'employee_id' => '003008',
                'name' => 'Solomon  Bassey Aniekan',
                'position' => 'Human Resources Officer',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'employee_id' => '002236',
                'name' => 'Udeme Lawrence Akama',
                'position' => 'Human Resources Officer',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'employee_id' => '002100',
                'name' => 'Uyime  Ukpong',
                'position' => 'Executive Assistant',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'employee_id' => '000032',
                'name' => 'Adeniyi  Afolabi',
                'position' => 'HR/ADMIN  Chief',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            27 => 
            array (
                'id' => 28,
                'employee_id' => '000994',
                'name' => 'Ahmet  Fatih Oztoprak',
                'position' => 'ACCOUNTING OFFICER',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'employee_id' => '000893',
                'name' => 'RAYMOND AKPABIO',
                'position' => 'Human Resources Officer SR',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            29 => 
            array (
                'id' => 30,
                'employee_id' => '001568',
                'name' => 'IBRAHIM UBA',
                'position' => 'procurement Supervisor',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            30 => 
            array (
                'id' => 31,
                'employee_id' => '002235',
                'name' => 'Ubong  Fabien Ekeruke',
                'position' => 'procurement officer',
                'project_id' => 12,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            31 => 
            array (
                'id' => 32,
                'employee_id' => '002352',
                'name' => 'Ibrahim Cabar',
                'position' => 'Warehouse Chief',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            32 => 
            array (
                'id' => 33,
                'employee_id' => '001724',
                'name' => 'Emmanuel Akpan',
                'position' => 'architec',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            33 => 
            array (
                'id' => 34,
                'employee_id' => '002598',
                'name' => 'Frances  Ikeji',
                'position' => 'IT Officer',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            34 => 
            array (
                'id' => 35,
                'employee_id' => '002725',
                'name' => 'Ime Sunday Iteh',
                'position' => 'IT Officer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            35 => 
            array (
                'id' => 36,
                'employee_id' => '001767',
                'name' => 'Deborah  Mark',
                'position' => 'IT Specialist',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            36 => 
            array (
                'id' => 37,
                'employee_id' => '003022',
                'name' => 'Bassey  Ekpo',
                'position' => 'IT Specialist',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            37 => 
            array (
                'id' => 38,
                'employee_id' => '02223',
                'name' => 'Patrick  Udo',
                'position' => 'IT  Supervisor',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            38 => 
            array (
                'id' => 39,
                'employee_id' => '003103',
                'name' => 'Cemal  Diragan',
                'position' => 'Mechanical  Foreman',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            39 => 
            array (
                'id' => 40,
                'employee_id' => '001436',
                'name' => 'Can  Ozsuphandag',
                'position' => 'Warehouse and Logistic  Chief',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            40 => 
            array (
                'id' => 41,
                'employee_id' => '000056',
                'name' => 'Abasiodu Jonah',
                'position' => 'IT Officer',
                'project_id' => 7,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            41 => 
            array (
                'id' => 42,
                'employee_id' => '003544',
                'name' => 'David  Enu',
                'position' => 'Accountant',
                'project_id' => 14,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            42 => 
            array (
                'id' => 43,
                'employee_id' => '001514',
                'name' => 'Clement  Jhonny',
                'position' => 'Warehouse Officer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            43 => 
            array (
                'id' => 44,
                'employee_id' => '002239',
                'name' => 'Emem  Obot',
                'position' => 'Cost Control Officer',
                'project_id' => 10,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            44 => 
            array (
                'id' => 45,
                'employee_id' => '003596',
                'name' => 'Ediongsenyene Edet',
                'position' => 'Logistice Supervisor',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            45 => 
            array (
                'id' => 46,
                'employee_id' => '003476',
                'name' => 'Henry  Nsofor',
                'position' => 'procurement officer',
                'project_id' => 14,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            46 => 
            array (
                'id' => 47,
                'employee_id' => '002826',
                'name' => 'Lewis  Aniekan Ekwere',
                'position' => 'Warehouse Officer',
                'project_id' => 10,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            47 => 
            array (
                'id' => 48,
                'employee_id' => '001809',
                'name' => 'Mikail  Tokmak',
                'position' => 'Accounting Chief',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            48 => 
            array (
                'id' => 49,
                'employee_id' => '002181',
                'name' => 'Monica  Ntewo',
                'position' => 'Camp supervisor',
                'project_id' => 8,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 01:00:00',
                'updated_at' => '2019-07-30 01:00:00',
            ),
            49 => 
            array (
                'id' => 50,
                'employee_id' => '00947',
                'name' => 'Kufre  Udo',
                'position' => 'Quantiity Surveyor',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            50 => 
            array (
                'id' => 51,
                'employee_id' => '002904',
                'name' => 'Daniel  Etteh',
                'position' => 'Architec',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            51 => 
            array (
                'id' => 52,
                'employee_id' => '000038',
                'name' => 'Inimfon  Obot',
                'position' => 'Civil  Engineer',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            52 => 
            array (
                'id' => 53,
                'employee_id' => '002943',
                'name' => 'Mfoniso  Robert',
                'position' => 'Warehouse Officer',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            53 => 
            array (
                'id' => 54,
                'employee_id' => '002918',
                'name' => 'Murak   Teke',
                'position' => 'HSE Chief',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            54 => 
            array (
                'id' => 55,
                'employee_id' => '001054',
                'name' => 'Nde  Santos',
                'position' => 'Mechanical  Engineer',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            55 => 
            array (
                'id' => 56,
                'employee_id' => '003046',
                'name' => 'Etim  Aniebiet  Bassey',
                'position' => 'Lab technichian',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            56 => 
            array (
                'id' => 57,
                'employee_id' => '003369',
                'name' => 'Malcolm  Essien',
                'position' => 'IT Officer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 01:00:00',
                'updated_at' => '2019-07-31 01:00:00',
            ),
            57 => 
            array (
                'id' => 58,
                'employee_id' => '003132',
                'name' => 'NKEREUWEM  OKON',
                'position' => 'Site Engeneer',
                'project_id' => 13,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-08-29 01:00:00',
                'updated_at' => '2019-08-29 01:00:00',
            ),
            58 => 
            array (
                'id' => 59,
                'employee_id' => '003717',
                'name' => 'Ofonime  Okon  Umoadiaemu',
                'position' => 'Logistice Officer',
                'project_id' => 11,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-08-30 01:00:00',
                'updated_at' => '2019-08-30 01:00:00',
            ),
            59 => 
            array (
                'id' => 60,
                'employee_id' => '002327',
                'name' => 'GODWIN  AKPAN',
                'position' => 'Media  Specialist',
                'project_id' => 1,
                'active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-08-30 01:00:00',
                'updated_at' => '2019-08-30 01:00:00',
            ),
        ));
        
        
    }
}