<?php

use Illuminate\Database\Seeder;

class InventoryHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inventory_histories')->delete();
        
        \DB::table('inventory_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'issue_date' => '2019-07-29',
                'employee_id' => 1,
                'equipment_id' => 1,
                'project_id' => 1,
                'situation_id' => 4,
                'projectTo_id' => 1,
                'approvedby' => 'Ndiana Isong',
                'remarks' => 'Currently working at Head Office, Uyo',
                'user_id' => 3,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-29 15:05:40',
                'updated_at' => '2019-07-29 15:08:26',
            ),
            1 => 
            array (
                'id' => 2,
                'issue_date' => '2017-06-08',
                'employee_id' => 36,
                'equipment_id' => 3,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'IT  supervisor',
                'remarks' => 'Deborah mark is an employee of VKS',
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 12:08:41',
                'updated_at' => '2019-07-31 12:08:41',
            ),
            2 => 
            array (
                'id' => 3,
                'issue_date' => '2017-11-20',
                'employee_id' => 38,
                'equipment_id' => 34,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'IT MANAGER',
                'remarks' => 'Mr patrick is a staff is VKS',
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 12:22:31',
                'updated_at' => '2019-07-31 12:23:32',
            ),
            3 => 
            array (
                'id' => 4,
                'issue_date' => '2017-12-19',
                'employee_id' => 44,
                'equipment_id' => 43,
                'project_id' => 10,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Cost manager',
                'remarks' => 'Emem  Obot is a worker of VKS',
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 12:47:23',
                'updated_at' => '2019-07-31 12:47:23',
            ),
            4 => 
            array (
                'id' => 5,
                'issue_date' => '2019-07-14',
                'employee_id' => 57,
                'equipment_id' => 64,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'IT MANAGER',
                'remarks' => 'Malcolm  Essien is a staff of VKS',
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 12:55:45',
                'updated_at' => '2019-07-31 12:55:45',
            ),
            5 => 
            array (
                'id' => 6,
                'issue_date' => '2019-08-29',
                'employee_id' => 34,
                'equipment_id' => 72,
                'project_id' => 8,
                'situation_id' => 2,
                'projectTo_id' => 13,
                'approvedby' => 'IT MANAGER',
                'remarks' => 'Frances  Ikeji is a staff of VKS',
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 13:01:00',
                'updated_at' => '2019-08-29 09:25:32',
            ),
            6 => 
            array (
                'id' => 7,
                'issue_date' => '2018-03-20',
                'employee_id' => 9,
                'equipment_id' => 62,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Project Cordinator',
                'remarks' => 'Adebayor  Mustapha is a staff of VKS',
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-31 13:49:27',
                'updated_at' => '2019-07-31 13:49:27',
            ),
            7 => 
            array (
                'id' => 8,
                'issue_date' => '2016-10-11',
                'employee_id' => 4,
                'equipment_id' => 53,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Project Cordinator',
                'remarks' => 'Alhassan  Ahmad is a staff is a staff  VKS',
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 07:46:47',
                'updated_at' => '2019-08-01 07:47:52',
            ),
            8 => 
            array (
                'id' => 9,
                'issue_date' => '2018-04-03',
                'employee_id' => 8,
                'equipment_id' => 72,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 8,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 07:53:58',
                'updated_at' => '2019-08-01 07:53:58',
            ),
            9 => 
            array (
                'id' => 10,
                'issue_date' => '2017-12-19',
                'employee_id' => 5,
                'equipment_id' => 84,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 8,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 07:56:03',
                'updated_at' => '2019-08-01 07:56:03',
            ),
            10 => 
            array (
                'id' => 11,
                'issue_date' => '2018-10-18',
                'employee_id' => 7,
                'equipment_id' => 2,
                'project_id' => 12,
                'situation_id' => 1,
                'projectTo_id' => 12,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 07:59:44',
                'updated_at' => '2019-08-01 07:59:44',
            ),
            11 => 
            array (
                'id' => 12,
                'issue_date' => '2019-01-08',
                'employee_id' => 3,
                'equipment_id' => 4,
                'project_id' => 1,
                'situation_id' => 1,
                'projectTo_id' => 1,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:02:47',
                'updated_at' => '2019-08-01 08:02:47',
            ),
            12 => 
            array (
                'id' => 13,
                'issue_date' => '2018-04-03',
                'employee_id' => 10,
                'equipment_id' => 72,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:05:12',
                'updated_at' => '2019-08-01 08:05:12',
            ),
            13 => 
            array (
                'id' => 14,
                'issue_date' => '2019-01-23',
                'employee_id' => 12,
                'equipment_id' => 2,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:28:02',
                'updated_at' => '2019-08-01 08:28:02',
            ),
            14 => 
            array (
                'id' => 15,
                'issue_date' => '2018-04-05',
                'employee_id' => 13,
                'equipment_id' => 89,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:29:29',
                'updated_at' => '2019-08-01 08:29:29',
            ),
            15 => 
            array (
                'id' => 16,
                'issue_date' => '2018-01-29',
                'employee_id' => 14,
                'equipment_id' => 76,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:31:15',
                'updated_at' => '2019-08-01 08:31:15',
            ),
            16 => 
            array (
                'id' => 17,
                'issue_date' => '2018-01-26',
                'employee_id' => 15,
                'equipment_id' => 2,
                'project_id' => 10,
                'situation_id' => 1,
                'projectTo_id' => 10,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:32:41',
                'updated_at' => '2019-08-01 08:32:41',
            ),
            17 => 
            array (
                'id' => 18,
                'issue_date' => '2017-06-13',
                'employee_id' => 16,
                'equipment_id' => 1,
                'project_id' => 11,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:34:18',
                'updated_at' => '2019-08-01 08:34:18',
            ),
            18 => 
            array (
                'id' => 19,
                'issue_date' => '2018-03-01',
                'employee_id' => 17,
                'equipment_id' => 64,
                'project_id' => 11,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:36:09',
                'updated_at' => '2019-08-01 08:36:09',
            ),
            19 => 
            array (
                'id' => 20,
                'issue_date' => '2018-08-28',
                'employee_id' => 18,
                'equipment_id' => 23,
                'project_id' => 11,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:38:57',
                'updated_at' => '2019-08-01 08:38:57',
            ),
            20 => 
            array (
                'id' => 21,
                'issue_date' => '2018-04-05',
                'employee_id' => 19,
                'equipment_id' => 2,
                'project_id' => 11,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:40:27',
                'updated_at' => '2019-08-01 08:40:27',
            ),
            21 => 
            array (
                'id' => 22,
                'issue_date' => '2018-02-10',
                'employee_id' => 22,
                'equipment_id' => 2,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 8,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:45:15',
                'updated_at' => '2019-08-01 08:45:15',
            ),
            22 => 
            array (
                'id' => 23,
                'issue_date' => '2018-04-30',
                'employee_id' => 23,
                'equipment_id' => 2,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 8,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 08:59:53',
                'updated_at' => '2019-08-01 08:59:53',
            ),
            23 => 
            array (
                'id' => 24,
                'issue_date' => '2017-12-12',
                'employee_id' => 25,
                'equipment_id' => 2,
                'project_id' => 11,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Project Cordinator',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-01 09:13:25',
                'updated_at' => '2019-08-01 09:13:25',
            ),
            24 => 
            array (
                'id' => 25,
                'issue_date' => '2019-08-02',
                'employee_id' => 26,
                'equipment_id' => 96,
                'project_id' => 1,
                'situation_id' => 1,
                'projectTo_id' => 1,
                'approvedby' => 'Uyime',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 07:29:45',
                'updated_at' => '2019-08-02 08:19:32',
            ),
            25 => 
            array (
                'id' => 26,
                'issue_date' => '2019-08-02',
                'employee_id' => 28,
                'equipment_id' => 76,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Ahmet  Oztoprak',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 07:34:38',
                'updated_at' => '2019-08-02 08:19:11',
            ),
            26 => 
            array (
                'id' => 27,
                'issue_date' => '2019-08-02',
                'employee_id' => 29,
                'equipment_id' => 2,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Raymond  Akpabio',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 07:38:06',
                'updated_at' => '2019-08-02 08:18:41',
            ),
            27 => 
            array (
                'id' => 28,
                'issue_date' => '2019-08-02',
                'employee_id' => 30,
                'equipment_id' => 2,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Ibrahim Ringim',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 07:40:35',
                'updated_at' => '2019-08-02 08:18:05',
            ),
            28 => 
            array (
                'id' => 29,
                'issue_date' => '2018-02-01',
                'employee_id' => 31,
                'equipment_id' => 2,
                'project_id' => 12,
                'situation_id' => 1,
                'projectTo_id' => 12,
                'approvedby' => 'Ubong Fabian',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 08:23:16',
                'updated_at' => '2019-08-02 08:23:16',
            ),
            29 => 
            array (
                'id' => 30,
                'issue_date' => '2018-02-19',
                'employee_id' => 32,
                'equipment_id' => 2,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Ibrahim  Cabar',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 08:25:44',
                'updated_at' => '2019-08-02 08:25:44',
            ),
            30 => 
            array (
                'id' => 31,
                'issue_date' => '2017-06-09',
                'employee_id' => 33,
                'equipment_id' => 2,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 8,
                'approvedby' => 'Emmanuel  Akpan',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 08:27:59',
                'updated_at' => '2019-08-02 08:27:59',
            ),
            31 => 
            array (
                'id' => 32,
                'issue_date' => '2018-12-13',
                'employee_id' => 39,
                'equipment_id' => 2,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Cemal Diragan',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:33:52',
                'updated_at' => '2019-08-02 12:33:52',
            ),
            32 => 
            array (
                'id' => 33,
                'issue_date' => '2016-07-28',
                'employee_id' => 40,
                'equipment_id' => 111,
                'project_id' => 1,
                'situation_id' => 1,
                'projectTo_id' => 1,
                'approvedby' => 'Can  OZSUPHANDAG',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:38:35',
                'updated_at' => '2019-08-02 12:38:35',
            ),
            33 => 
            array (
                'id' => 34,
                'issue_date' => '2018-05-14',
                'employee_id' => 41,
                'equipment_id' => 80,
                'project_id' => 7,
                'situation_id' => 1,
                'projectTo_id' => 7,
                'approvedby' => 'Abasiodu  Jonah',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:41:23',
                'updated_at' => '2019-08-02 12:41:23',
            ),
            34 => 
            array (
                'id' => 35,
                'issue_date' => '2019-04-12',
                'employee_id' => 42,
                'equipment_id' => 45,
                'project_id' => 14,
                'situation_id' => 1,
                'projectTo_id' => 14,
                'approvedby' => 'David  Enu',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:45:46',
                'updated_at' => '2019-08-02 12:45:46',
            ),
            35 => 
            array (
                'id' => 36,
                'issue_date' => '2017-04-17',
                'employee_id' => 43,
                'equipment_id' => 7,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Clement Johnny',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:49:28',
                'updated_at' => '2019-08-02 12:49:28',
            ),
            36 => 
            array (
                'id' => 37,
                'issue_date' => '2017-12-19',
                'employee_id' => 44,
                'equipment_id' => 52,
                'project_id' => 10,
                'situation_id' => 1,
                'projectTo_id' => 10,
                'approvedby' => 'Emem Obot',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:51:38',
                'updated_at' => '2019-08-02 12:51:38',
            ),
            37 => 
            array (
                'id' => 38,
                'issue_date' => '2019-05-18',
                'employee_id' => 45,
                'equipment_id' => 2,
                'project_id' => 1,
                'situation_id' => 1,
                'projectTo_id' => 1,
                'approvedby' => 'Ediongsenyene  Edet',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:53:53',
                'updated_at' => '2019-08-02 12:53:53',
            ),
            38 => 
            array (
                'id' => 39,
                'issue_date' => '2019-04-03',
                'employee_id' => 46,
                'equipment_id' => 2,
                'project_id' => 11,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Henry Nsofor',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 12:57:54',
                'updated_at' => '2019-08-02 12:57:54',
            ),
            39 => 
            array (
                'id' => 40,
                'issue_date' => '2018-08-09',
                'employee_id' => 47,
                'equipment_id' => 7,
                'project_id' => 10,
                'situation_id' => 1,
                'projectTo_id' => 10,
                'approvedby' => 'Lewis Ekwere',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 13:00:05',
                'updated_at' => '2019-08-02 13:00:05',
            ),
            40 => 
            array (
                'id' => 41,
                'issue_date' => '2017-08-11',
                'employee_id' => 48,
                'equipment_id' => 2,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 8,
                'approvedby' => 'Mikail  Tokmak',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 13:01:45',
                'updated_at' => '2019-08-02 13:01:45',
            ),
            41 => 
            array (
                'id' => 42,
                'issue_date' => '2018-08-24',
                'employee_id' => 49,
                'equipment_id' => 2,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 8,
                'approvedby' => 'Monica  Ntewo',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 13:03:53',
                'updated_at' => '2019-08-02 13:03:53',
            ),
            42 => 
            array (
                'id' => 43,
                'issue_date' => '2017-03-14',
                'employee_id' => 50,
                'equipment_id' => 2,
                'project_id' => 13,
                'situation_id' => 1,
                'projectTo_id' => 13,
                'approvedby' => 'Kufre  Udo',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 13:05:40',
                'updated_at' => '2019-08-02 13:05:40',
            ),
            43 => 
            array (
                'id' => 44,
                'issue_date' => '2018-08-25',
                'employee_id' => 51,
                'equipment_id' => 73,
                'project_id' => 1,
                'situation_id' => 1,
                'projectTo_id' => 1,
                'approvedby' => 'Daniel Etteh',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 13:08:29',
                'updated_at' => '2019-08-02 13:08:29',
            ),
            44 => 
            array (
                'id' => 45,
                'issue_date' => '2018-10-29',
                'employee_id' => 52,
                'equipment_id' => 64,
                'project_id' => 8,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Inimfon Obot',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 13:19:47',
                'updated_at' => '2019-08-02 13:19:47',
            ),
            45 => 
            array (
                'id' => 46,
                'issue_date' => '2018-11-12',
                'employee_id' => 53,
                'equipment_id' => 81,
                'project_id' => 1,
                'situation_id' => 1,
                'projectTo_id' => 1,
                'approvedby' => 'Mfoniso',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 15:23:09',
                'updated_at' => '2019-08-02 15:23:09',
            ),
            46 => 
            array (
                'id' => 47,
                'issue_date' => '2019-08-02',
                'employee_id' => 54,
                'equipment_id' => 88,
                'project_id' => 11,
                'situation_id' => 1,
                'projectTo_id' => 11,
                'approvedby' => 'Murat Teke',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 15:24:40',
                'updated_at' => '2019-08-02 15:24:40',
            ),
            47 => 
            array (
                'id' => 48,
                'issue_date' => '2019-02-20',
                'employee_id' => 56,
                'equipment_id' => 2,
                'project_id' => 1,
                'situation_id' => 1,
                'projectTo_id' => 1,
                'approvedby' => 'Etim Aniebiet',
                'remarks' => NULL,
                'user_id' => 14,
                'document_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-02 15:27:15',
                'updated_at' => '2019-08-02 15:27:15',
            ),
        ));
        
        
    }
}